"""Oracle adapter (oracledb) — the hardest semantics (CONCEPT.md §10).

Oracle commits DDL **implicitly** — there is no all-or-nothing rollback for a multi-statement
deploy. ``apply`` therefore runs statements sequentially (each self-commits); a mid-deploy
failure leaves earlier statements applied. Mitigate with verify steps and idempotent/guarded
DDL — never rely on rollback here.

Other Oracle specifics handled in this adapter:

* no ``CREATE TABLE IF NOT EXISTS`` → the ledger is created via a guarded PL/SQL block that
  swallows ORA-00955 ("name already used");
* ``ALTER TABLE … ADD col`` with Oracle ordering (``DEFAULT`` before ``NOT NULL``);
* unquoted identifiers are stored upper-case → introspection normalizes case;
* python-oracledb rejects a trailing ``;`` on plain SQL but needs the ``;`` *inside* PL/SQL →
  terminators are stripped for SQL and PL/SQL blocks are kept intact;
* init scripts are split on SQL*Plus ``/`` block terminators.

Requires the ``oracle`` extra (oracledb). Not yet e2e-verified against a live instance.
"""
from __future__ import annotations

import re

from sqlalchemy import inspect, text

from dbly.adapters.base import Adapter, Column
from dbly.model import ObjectId, ObjectKind

_SLASH_RE = re.compile(r"(?m)^\s*/\s*$")
_PLSQL_RE = re.compile(
    r"^\s*(CREATE\s+(OR\s+REPLACE\s+)?(EDITIONABLE\s+|NONEDITIONABLE\s+)?"
    r"(PROCEDURE|FUNCTION|PACKAGE|TRIGGER|TYPE)\b|BEGIN\b|DECLARE\b)",
    re.IGNORECASE,
)

_STATE_BLOCK = """
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE dbly_state (
            id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            deployed_sha VARCHAR2(64) NOT NULL,
            migration_id VARCHAR2(200),
            applied_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;  -- ORA-00955: name already used
END;
"""


def _is_plsql(stmt: str) -> bool:
    return bool(_PLSQL_RE.match(stmt))


def strip_terminator(stmt: str) -> str:
    """Strip a trailing ``;`` from plain SQL; leave PL/SQL blocks (END;) intact."""
    s = stmt.strip()
    if not _is_plsql(s) and s.endswith(";"):
        return s[:-1].rstrip()
    return s


def split_oracle_script(script: str) -> list[str]:
    """Split an init script into executable units.

    PL/SQL blocks are terminated by a lone ``/`` (SQL*Plus convention) and run whole; plain
    SQL between terminators is split on ``;``. Semicolons inside string literals are a known
    edge case (rare in init scripts).
    """
    out: list[str] = []
    for chunk in _SLASH_RE.split(script):
        s = chunk.strip()
        if not s:
            continue
        if _is_plsql(s):
            out.append(s)
        else:
            out.extend(st.strip() for st in s.split(";") if st.strip())
    return out


class OracleAdapter(Adapter):
    transactional_ddl = False  # DDL auto-commits — no rollback

    @staticmethod
    def _norm(ident: str | None) -> str | None:
        # unquoted Oracle identifiers are upper-cased on storage
        return ident.upper() if ident else ident

    def table_exists(self, schema: str | None, name: str) -> bool:
        return inspect(self.engine).has_table(self._norm(name), schema=self._norm(schema))

    def get_columns(self, schema: str | None, name: str) -> list[Column]:
        cols = inspect(self.engine).get_columns(self._norm(name), schema=self._norm(schema))
        return [
            Column(
                name=c["name"],
                type=str(c["type"]),
                nullable=bool(c["nullable"]),
                default=None if c.get("default") is None else str(c["default"]),
            )
            for c in cols
        ]

    def has_object(self, kind: ObjectKind, schema: str | None, name: str) -> bool:
        n = name.upper()
        s = schema.upper() if schema else None
        if kind is ObjectKind.INDEX:
            q = "SELECT 1 FROM all_indexes WHERE index_name = :n AND (:s IS NULL OR owner = :s)"
        elif kind is ObjectKind.SEQUENCE:
            q = ("SELECT 1 FROM all_sequences "
                 "WHERE sequence_name = :n AND (:s IS NULL OR sequence_owner = :s)")
        else:
            q = "SELECT 1 FROM all_objects WHERE object_name = :n AND (:s IS NULL OR owner = :s)"
        with self.engine.connect() as conn:
            return conn.execute(text(q), {"n": n, "s": s}).first() is not None

    def add_column_sql(self, table: ObjectId, col: Column) -> str:
        parts = [f"ALTER TABLE {table} ADD {col.name} {col.type}"]
        if col.default is not None:
            parts.append(f"DEFAULT {col.default}")  # Oracle: DEFAULT before NOT NULL
        if not col.nullable:
            parts.append("NOT NULL")
        return " ".join(parts) + ";"

    def apply(self, statements: list[str]) -> None:
        # No transactional rollback (DDL auto-commits). Sequential; commit covers any DML.
        with self.engine.connect() as conn:
            for stmt in statements:
                s = strip_terminator(stmt)
                if s:
                    conn.exec_driver_sql(s)
            conn.commit()

    def run_init_script(self, script: str) -> None:
        with self.engine.connect() as conn:
            for stmt in split_oracle_script(script):
                conn.exec_driver_sql(stmt)
            conn.commit()

    def state_table_ddl(self) -> str:
        return _STATE_BLOCK.strip() + "\n/"  # '/' terminates the block for a SQL*Plus hand-run

    def record_deploy_sql(self, ref: str) -> str:
        return f"INSERT INTO dbly_state (deployed_sha) VALUES ('{ref.replace(chr(39), chr(39) * 2)}');"

    def ensure_state_table(self) -> None:
        with self.engine.connect() as conn:
            conn.exec_driver_sql(_STATE_BLOCK.strip())
            conn.commit()

    def get_deployed_ref(self) -> str | None:
        self.ensure_state_table()
        with self.engine.connect() as conn:
            row = conn.exec_driver_sql(
                "SELECT deployed_sha FROM dbly_state "
                "ORDER BY applied_at DESC, id DESC FETCH FIRST 1 ROW ONLY"
            ).first()
        return row[0] if row else None

    def record_deploy(self, ref: str, migration_ids: list[str]) -> None:
        self.ensure_state_table()
        with self.engine.connect() as conn:
            for mid in (migration_ids or [None]):
                conn.execute(
                    text(
                        "INSERT INTO dbly_state (deployed_sha, migration_id) "
                        "VALUES (:sha, :mid)"
                    ),
                    {"sha": ref, "mid": mid},
                )
            conn.commit()
